### ISSUE TITLE
Status Code 429

### ISSUE THREAD

**Issue by aidulcandra** [imRohan/Pantry#122]
Hello, I've been using Pantry's rest api for about a month now. But these days I've been getting status code 429 when requesting a basket.. I just wanna know what the call rate limit is. Thank you.

**Comment by imRohan** [comment]
Hi @aidulcandra 

Due to a few users requesting basket contents every few milliseconds, I had to implement rate-limiting for that route.

Currently, users will be able to request the contents of a basket 20 times before the rate-limiting kicks in.

Can you describe what you're experiencing on your end? You should be able to get the contents of your basket after waiting for around 20seconds between cooldowns.

**Comment by aidulcandra** [comment]
> Hi @aidulcandra
> 
> Currently, users will be able to request the contents of a basket 20 times before the rate-limiting kicks in. (20 times in ~20 seconds).
> 
> I'd advise you to limit fetching the contents of a basket to 1 request per second.
> 
> You should be able to get the contents of your basket after waiting for around 20 seconds between cooldowns.

I see... well in my code, I first check for the list of baskets using GET /pantry/PANTRY_ID
This one always return status code 200

And then if the basket that I'm looking for is there.. it will get the contents of the basket using GET /pantry/PANTRY_ID/basket/BASKET_NAME
Now this one will receive code 429 (most of the time)

So I only have those 2 requests within the 20s limit.
I already tried waiting for more than 20s before restarting the code again, but it still responds with 429

**Comment by imRohan** [comment]
Understood.

I took a look and it seems like I may have been too strict with my rate limiting rules.

I've updated Pantry to limit requests to every 1/2 second 👍
