### ISSUE TITLE
Slow Site and Timeout Errors

### ISSUE THREAD

**Issue by itsMikeLowrey** [imRohan/Pantry#178]
Hi,
The site is loading really slowly when I access it from the getPantry site. When I access it from my app, my serverless functions error out due to the api taking too long to respond. This delay makes the site functionality unusable.

**Comment by imRohan** [comment]
Hi @itsMikeLowrey 

Yup, noticing that Pantry has been getting a lot of traffic today and our tiny server is having a hard time keeping up with the number of requests.

Since it's a free service, I am not in a position to upgrade the servers at this moment. Apologies.

Feel free to implement a request retries with exponential backoff to your worker to help with the delays.

Pantry should come back up soon, just bogged down at the moment.
