### ISSUE TITLE
My Pantry has gone for no reason

### ISSUE THREAD

**Issue by abdipr** [imRohan/Pantry#210]
yesterday I was still able to log into my Pantry with my PantryID, no problems occurred. but today I tried to log in again with my PantryID, instead there was an alert pop ups that said “Login Failed. Is your PantryID correct?”. that's very strange because before (yesterday) it was running normally with no problems. and I'm not doing anything, just making projects that use Pantry as storage, as usual.

I'm feeling very sad for my database that was in my Pantry account, because it was quite important to me, and I didn't have a back up. I want to register again with the same email but I'm afraid of destroying existing information, so maybe I'll just stay until there is a proper solution to this problem.

hopefully this problem can be enlightened, and I want to use it again without problems. I'm glad there is a Pantry so please fix this and try to get my data that was there back :)

**note:** the last activity in my Pantry was less than 7 days, I just made a new basket there and then used it in my project. but now it's all gone...

![Email Screenshot](https://github.com/user-attachments/assets/7812bc64-9853-4b8b-baad-cfc745c66b1f)
![Alert Screenshot](https://github.com/user-attachments/assets/6818dda4-670c-4c8f-acb8-e2725b5e2257)

**Comment by imRohan** [comment]
@abdipr Sorry to hear that. However, due to an unexpected failure by the host of our servers, the databases were purged, and I do not have a backup available. Please keep in mind that Pantry is a free service and we do not guarantee data redundancy.

I am deeply sorry for the inconvenience this has caused, I too lost some data as well. Currently, I am working with the hosting provider to see if i can recover any data - however it's not looking promising.

**Comment by abdipr** [comment]
alright then, hopefully in the future there won't be any more problems for Pantry, because I love using this service :)
